image: node:20

stages:
  - install
  - build
  - pages
  - cleanup

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .bun
    - node_modules/
    - bun.lockb

build_project:
  stage: build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .bun
      - node_modules/
      - bun.lockb

  script:
    - echo "Installing dependencies for build..."
    - npm install -g bun
    - bun install --frozen-lockfile
    - echo "Building project..."
    - bun run build:version-editor
  artifacts:
    name: "build-${CI_COMMIT_REF_SLUG}"
    paths:
      - dist/apps/version-editor
    expire_in: 1 week
