image: node:20

stages:
  - install
  - build
  - pages
  - cleanup

cache: &bun_cache
  key:
    files:
      - bun.lockb
  policy: pull
  paths:
    - 'node_modules/'

install_bun:
  stage: install
  script:
    - npm install -g bun

# Install dependencies
install dependencies:
  stage: install
  interruptible: false
  cache:
    <<: *bun_cache
    policy: pull-push
  script:
    - node -v
    - bun install --frozen-lockfile --no-progress --non-interactive


build_project:
  stage: build
  script:
    - echo "Building project..."
    - bun run build:version-editor
  artifacts:
    name: "build-${CI_COMMIT_REF_SLUG}"
    paths:
      - dist/apps/version-editor
    expire_in: 1 week
