image: node:20

stages:
  - install_dependencies
  - build
  - pages
  - cleanup

# Cache configuration for Bun dependencies
cache: &bun_cache
  key:
    files:
      - bun.lockb
  paths:
    - node_modules/
  policy: pull-push

# Install Bun and dependencies using Bun
install_dependencies:
  stage: install_dependencies
  interruptible: false
  cache:
    <<: *bun_cache
  script:
    - npm install -g bun
    - node -v
    - bun install --frozen-lockfile --no-progress --non-interactive

# Build project using Bun
build_project:
  stage: build
  script:
    - echo "Building project..."
    - bun run build:version-editor
  artifacts:
    name: "build-${CI_COMMIT_REF_SLUG}"
    paths:
      - dist/apps/version-editor
    expire_in: 1 week
