image: node:20

stages:
  - install
  - build
  - pages
  - cleanup

install_dependencies:
  stage: install
  script:
    - echo "Installing dependencies..."
    - npm ci

build_project:
  stage: build
  script:
    - echo "Installing dependencies for build..."
    - npm install -g bun
    - bun install --frozen-lockfile
    - echo "Building project..."
    - bun run build:version-editor
  artifacts:
    name: "build-${CI_COMMIT_REF_SLUG}"
    paths:
      - packages/distribution/build/
    expire_in: 1 week

