/**
 * CoMPAS SCL Data Service History API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI } from '../runtime';
import type { OperationOpts } from '../runtime';
import type { DataResourceHistory, DataResourceSearch, DataResourcesResult } from '../models';
export interface RetrieveDataResourceByVersionRequest {
    id: string;
    version: string;
}
export interface RetrieveDataResourceHistoryRequest {
    id: string;
}
export interface SearchForResourcesRequest {
    dataResourceSearch: DataResourceSearch;
}
/**
 * no description
 */
export declare class HistoryApi extends BaseAPI {
    /**
     * Retrieve data resource for a specific version
     * Retrieve data resource for a specific version
     */
    retrieveDataResourceByVersion({ id, version }: RetrieveDataResourceByVersionRequest): Observable<Blob>;
    retrieveDataResourceByVersion({ id, version }: RetrieveDataResourceByVersionRequest, opts?: OperationOpts): Observable<AjaxResponse<Blob>>;
    /**
     * Trigger search enabled by the search filter
     * Trigger search enabled by the search filter
     */
    retrieveDataResourceHistory({ id }: RetrieveDataResourceHistoryRequest): Observable<DataResourceHistory>;
    retrieveDataResourceHistory({ id }: RetrieveDataResourceHistoryRequest, opts?: OperationOpts): Observable<AjaxResponse<DataResourceHistory>>;
    /**
     * Trigger search enabled by the search filter
     * Trigger search enabled by the search filter
     */
    searchForResources({ dataResourceSearch }: SearchForResourcesRequest): Observable<DataResourcesResult>;
    searchForResources({ dataResourceSearch }: SearchForResourcesRequest, opts?: OperationOpts): Observable<AjaxResponse<DataResourcesResult>>;
}
