"use strict";
// tslint:disable
/**
 * CoMPAS SCL Data Service History API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.HistoryApi = void 0;
const runtime_1 = require("../runtime");
/**
 * no description
 */
class HistoryApi extends runtime_1.BaseAPI {
    retrieveDataResourceByVersion({ id, version }, opts) {
        (0, runtime_1.throwIfNullOrUndefined)(id, 'id', 'retrieveDataResourceByVersion');
        (0, runtime_1.throwIfNullOrUndefined)(version, 'version', 'retrieveDataResourceByVersion');
        const headers = {};
        return this.request({
            url: '/api/scl/{id}/version/{version}'.replace('{id}', (0, runtime_1.encodeURI)(id)).replace('{version}', (0, runtime_1.encodeURI)(version)),
            method: 'GET',
            headers,
            responseType: 'blob',
        }, opts === null || opts === void 0 ? void 0 : opts.responseOpts);
    }
    ;
    retrieveDataResourceHistory({ id }, opts) {
        (0, runtime_1.throwIfNullOrUndefined)(id, 'id', 'retrieveDataResourceHistory');
        const headers = {};
        return this.request({
            url: '/api/scl/{id}/versions'.replace('{id}', (0, runtime_1.encodeURI)(id)),
            method: 'GET',
            headers,
        }, opts === null || opts === void 0 ? void 0 : opts.responseOpts);
    }
    ;
    searchForResources({ dataResourceSearch }, opts) {
        (0, runtime_1.throwIfNullOrUndefined)(dataResourceSearch, 'dataResourceSearch', 'searchForResources');
        const headers = {
            'Content-Type': 'application/json',
        };
        return this.request({
            url: '/api/scl/search',
            method: 'POST',
            headers,
            body: dataResourceSearch,
        }, opts === null || opts === void 0 ? void 0 : opts.responseOpts);
    }
    ;
}
exports.HistoryApi = HistoryApi;
//# sourceMappingURL=HistoryApi.js.map