/**
 * CoMPAS SCL Data Service History API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * @export
 * @interface DataResource
 */
export interface DataResource {
    /**
     * Unique identifier
     * @type {string}
     * @memberof DataResource
     */
    uuid: string;
    /**
     * Name of the resource
     * @type {string}
     * @memberof DataResource
     */
    name: string;
    /**
     * Name of the author last changed the document
     * @type {string}
     * @memberof DataResource
     */
    author: string;
    /**
     * One of the supported types: SSD, IID, ICD, SCD, CID, SED, ISD, STD, etc.
     * @type {string}
     * @memberof DataResource
     */
    type: string;
    /**
     * Point in time of last modification/upload
     * @type {string}
     * @memberof DataResource
     */
    changedAt: string;
    /**
     * Generated version by the scl-data-service
     * @type {string}
     * @memberof DataResource
     */
    version: string;
    /**
     * Defines if a resource is available as download or version was created while uploading a file
     * @type {boolean}
     * @memberof DataResource
     */
    available: boolean;
    /**
     * Defines if a resource is marked as deleted
     * @type {boolean}
     * @memberof DataResource
     */
    deleted: boolean;
    /**
     * The location associated with the resource
     * @type {string}
     * @memberof DataResource
     */
    location?: string;
}
