/**
 * CoMPAS SCL Data Service History API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * @export
 * @interface DataResourceSearch
 */
export interface DataResourceSearch {
    /**
     * If uuid is set no other filter must be set
     * @type {string}
     * @memberof DataResourceSearch
     */
    uuid?: string;
    /**
     * Fulltext match set to one of the supported scl types: SSD, IID, ICD, SCD, CID, SED, ISD, STD, etc.
     * @type {string}
     * @memberof DataResourceSearch
     */
    type?: string;
    /**
     * Partially match allowed
     * @type {string}
     * @memberof DataResourceSearch
     */
    name?: string;
    /**
     * The location associated with the resource
     * @type {string}
     * @memberof DataResourceSearch
     */
    location?: string;
    /**
     * Fulltext match which can be retrieved via extra endpoint
     * @type {string}
     * @memberof DataResourceSearch
     */
    author?: string;
    /**
     * Starting date and time for filtering results. Use ISO 8601 format (e.g., 2024-10-22T14:48:00Z).
     * @type {string}
     * @memberof DataResourceSearch
     */
    from?: string;
    /**
     * Ending date and time for filtering results. Use ISO 8601 format (e.g., 2024-10-22T14:48:00Z).
     * @type {string}
     * @memberof DataResourceSearch
     */
    to?: string;
}
