/**
 * CoMPAS SCL Data Service History API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * @export
 * @interface ErrorResponseDto
 */
export interface ErrorResponseDto {
    /**
     * 2017-07-21T17:32:28Z.
     * @type {string}
     * @memberof ErrorResponseDto
     */
    timestamp: string;
    /**
     * @type {string}
     * @memberof ErrorResponseDto
     */
    code: string;
    /**
     * @type {string}
     * @memberof ErrorResponseDto
     */
    message: string;
}
