import { type InstanceDetails, TypeKind } from "./model";

export const INSTANCE_DESCRIPTIONS: Record<TypeKind, Record<string, InstanceDetails>> = {
    [TypeKind.LNodeType]: {
        LPHD: { "instance": "LPHD", "description": "Physical Device Status Information" },
        LLN0: { "instance": "LLN0", "description": "Logical Device Status Information" },
        LCCH: { "instance": "LCCH", "description": "Communication Channel Status Information" },
        LGOS: { "instance": "LGOS", "description": "GOOSE Subscription Status Information" },
        LSVS: { "instance": "LSVS", "description": "SMV-Stream Subscription Status Information" },
        LTIM: { "instance": "LTIM", "description": "Local Time Information of an IED" },
        LTMS: { "instance": "LTMS", "description": "Configuration & Supervision of Time synchronization in IED" },
        LTRK: { "instance": "LTRK", "description": "Server Status Information in an IED" },
        ANCR: { "instance": "ANCR", "description": "Regulation Functions for Petersen Coils" },
        ARCO: { "instance": "ARCO", "description": "Regulation Functions for Capacitor Banks" },
        ARIS: { "instance": "ARIS", "description": "General automatic wattmetric Increase with Thermal Supervision" },
        ATCC: { "instance": "ATCC", "description": "Transformator Tap Changer Regulation Functions" },
        AVCO: { "instance": "AVCO", "description": "General Voltage Regulation" },
        CALH: { "instance": "CALH", "description": "Management of Group Warnings and Alarms" },
        CCGR: { "instance": "CCGR", "description": "Control of Cooling Equipment (Fans, Pumps, etc.)" },
        CILO: { "instance": "CILO", "description": "Control of Interlocking Functions" },
        CPOW: { "instance": "CPOW", "description": "Measurement-Based Line Switching Control" },
        CSWI: { "instance": "CSWI", "description": "Control of Circuit Breakers and Disconnectors" },
        CSYN: { "instance": "CSYN", "description": "Control for Synchronizing conditions (Voltage, Frequency, Phase)" },
        FCNT: { "instance": "FCNT", "description": "Counting of Pulses Not Originating from the Power Grid" },
        FCSD: { "instance": "FCSD", "description": "Algorithms for Representing Curve-Shaped Value Pairs" },
        FFIL: { "instance": "FFIL", "description": "Filtering Functions for Incoming Signals" },
        FLIM: { "instance": "FLIM", "description": "Functions for Defining temporary/permanent limits for a Variable" },
        FPID: { "instance": "FPID", "description": "Functions for Handling Information for a PID-Controller" },
        FRMP: { "instance": "FRMP", "description": "Provides Ramp Functions" },
        FSCC: { "instance": "FSCC", "description": "Provides Scheduling Control Functions" },
        FSCH: { "instance": "FSCH", "description": "Offers Scheduling Methods" },
        FSPT: { "instance": "FSPT", "description": "General Node for Control and Regulation type Logical Nodes" },
        FXOT: { "instance": "FXOT", "description": "Handling of General Maximum Values" },
        FXUT: { "instance": "FXUT", "description": "Handling of General Minimum Values" },
        GAPC: { "instance": "GAPC", "description": "Generic Node for Control and Process Applications" },
        GGIO: { "instance": "GGIO", "description": "Generic Node for I/O Applications" },
        GLOG: { "instance": "GLOG", "description": "Generic Node for Recording and Logging" },
        GSAL: { "instance": "GSAL", "description": "Generic Node for Security Applications" },
        IARC: { "instance": "IARC", "description": "unctions for Trigger-Based Data Archiving" },
        IHMI: { "instance": "IHMI", "description": "Functions for HMI Communication" },
        ISAF: { "instance": "ISAF", "description": "Functions for Safety Alarms (Fire Detectors, Gas Sensors, etc.)" },
        ITCI: { "instance": "ITCI", "description": "Functions for telecontrol systems" },
        ITMI: { "instance": "ITMI", "description": "Functions for telemonitoring system" },
        ITPC: { "instance": "ITPC", "description": "Functions for Monitoring Communication Channels" },
        KFAN: { "instance": "KFAN", "description": "Control Functions for Fans" },
        KFIL: { "instance": "KFIL", "description": "Control Functions for Mechanical Filters" },
        KPMP: { "instance": "KPMP", "description": "Control Functions for Pumps" },
        KTNK: { "instance": "KTNK", "description": "Control Functions for Tanks (Water, Hydraulic, Pneumatic, etc.)" },
        KVLV: { "instance": "KVLV", "description": "Control Functions for Valves and Gates" },
        MENV: { "instance": "MENV", "description": "Measurement Functions for Emissions (Smoke, CO, CO₂, NOx, SOx)" },
        MFLK: { "instance": "MFLK", "description": "Measurement Functions of flicker inducing voltage fluctuations" },
        MFLW: { "instance": "MFLW", "description": "Functions for Flow Measurement (Liquids, Gas, Steam, etc.)" },
        MHAI: { "instance": "MHAI", "description": "Measurement Functions for Three-Phase Harmonic/interharmonic Oscillations" },
        MHAN: { "instance": "MHAN", "description": "Measurement Functions for Single-Phase Harmonic/interharmonic Oscillations" },
        MHET: { "instance": "MHET", "description": "General Temperature Measurement Functions of heat in Material (air, water etc.)" },
        MHYD: { "instance": "MHYD", "description": "Functions for Hydrometric Measurements" },
        MMDC: { "instance": "MMDC", "description": "Measurement Functions for DC Systems" },
        MMET: { "instance": "MMET", "description": "Functions for Meteorological Measurements/Informations" },
        MMTN: { "instance": "MMTN", "description": "Functions for Billing-Relevant Energy Measurement (Single-Phase)" },
        MMTR: { "instance": "MMTR", "description": "Functions for Billing-Relevant Energy Measurement (Three-Phase)" },
        MMXN: { "instance": "MMXN", "description": "Functions for Non-Phase-Specific Electrical Measurements" },
        MMXU: { "instance": "MMXU", "description": "Functions for electrical measurements in three-phase systems (Current, Voltage etc.)" },
        MSQI: { "instance": "MSQI", "description": "Functions for Phasor & asymmetry analysis (sequence & imbalance)" },
        PDIF: { "instance": "PDIF", "description": "Functions for Current Differential Protection" },
        PDIR: { "instance": "PDIR", "description": "Directional comparison for fault location" },
        PDIS: { "instance": "PDIS", "description": "Distance protection function" },
        PDOP: { "instance": "PDOP", "description": "Power-based overload protection function" },
        PDUP: { "instance": "PDUP", "description": "Power-based underload protection function" },
        PFRC: { "instance": "PFRC", "description": "Frequency protection function with rate-of-change (df/dt) monitoring" },
        PHAR: { "instance": "PHAR", "description": "Harmonic handling for differential protection (PDIF)" },
        PHIZ: { "instance": "PHIZ", "description": "Handling of high-impedance (resistance) insulation faults" },
        PIOC: { "instance": "PIOC", "description": "Instantaneous overcurrent protection" },
        PMRI: { "instance": "PMRI", "description": "Motor start-up protection" },
        PMSS: { "instance": "PMSS", "description": "Motor start-up protection for excessive starting time during start-up" },
        POPF: { "instance": "POPF", "description": "Overload protection based on power factor (cos φ)" },
        PPAM: { "instance": "PPAM", "description": "Asynchronism handling in generators" },
        PRTR: { "instance": "PRTR", "description": "Field short-circuit protection based on 6th harmonic detection" },
        PSCH: { "instance": "PSCH", "description": "Functions for higher-level protection schemes for lines" },
        PSDE: { "instance": "PSDE", "description": "Earthfault handling in compensated and isolated networks" },
        PSOF: { "instance": "PSOF", "description": "Protection Function Instantaneous tripping on switch-on-to-fault conditions" },
        PTDV: { "instance": "PTDV", "description": "Functions for Voltage Differential Protection" },
        PTEF: { "instance": "PTEF", "description": "Transient earth fault protection in compensated networks" },
        PTHF: { "instance": "PTHF", "description": "Thyristor protection" },
        PTOC: { "instance": "PTOC", "description": "Time-based overcurrent protection" },
        PTOF: { "instance": "PTOF", "description": "Overfrequency protection" },
        PTOV: { "instance": "PTOV", "description": "Overvoltage protection" },
        PTRC: { "instance": "PTRC", "description": "Functions for trip management" },
        PTTR: { "instance": "PTTR", "description": "Thermal overload protection" },
        PTUC: { "instance": "PTUC", "description": "Undercurrent/Underpower protection" },
        PTUF: { "instance": "PTUF", "description": "Underfrequency protection" },
        PTUV: { "instance": "PTUV", "description": "Undervoltage protection" },
        PUPF: { "instance": "PUPF", "description": "Underload protection based on power factor (cos φ)" },
        PVOC: { "instance": "PVOC", "description": "Voltage controlled time overcurrent protection" },
        PVPH: { "instance": "PVPH", "description": "Frequency-dependent voltage protection" },
        PZSU: { "instance": "PZSU", "description": "zero speed or underspeed protection (Actuator failure protection)" },
        QFVR: { "instance": "QFVR", "description": "Analysis of frequency variation" },
        QITR: { "instance": "QITR", "description": "Analysis of current transients" },
        QIUB: { "instance": "QIUB", "description": "Analysis of current unbalance variation" },
        QVTR: { "instance": "QVTR", "description": "Analysis of voltage transients" },
        QVUB: { "instance": "QVUB", "description": "Analysis of voltgae unbalance variation" },
        QVVR: { "instance": "QVVR", "description": "Analysis of voltage variations" },
        RADR: { "instance": "RADR", "description": "Control functions of an analog disturbance recorder channel" },
        RBDR: { "instance": "RBDR", "description": "Control functions of a binary disturbance recorder channel" },
        RBRF: { "instance": "RBRF", "description": "Control functions for breaker failure backup protection" },
        RDIR: { "instance": "RDIR", "description": "Provides directional input/information" },
        RDRE: { "instance": "RDRE", "description": "Control functions for disturbance recorder" },
        RDRS: { "instance": "RDRS", "description": "Supervision and control of disturbance recorder upload" },
        RFLO: { "instance": "RFLO", "description": "Fault location calculation functions (calculated in ohm)" },
        RMXU: { "instance": "RMXU", "description": "Calculation functions of process data for differential protection" },
        RPSB: { "instance": "RPSB", "description": "Blocking functions for differential protection during periodic fluctuations" },
        RREC: { "instance": "RREC", "description": "Auto-reclosing functions (AWE)" },
        RSYN: { "instance": "RSYN", "description": "Functions for synchrocheck based on voltage phasor comparison" },
        SARC: { "instance": "SARC", "description": "Arc monitoring and diagnostics" },
        SCBR: { "instance": "SCBR", "description": "Supervision of circuit breakers (position and wear)" },
        SIMG: { "instance": "SIMG", "description": "Supervision of gas-insulated equipment" },
        SIML: { "instance": "SIML", "description": "Supervision of liquid-insulated equipment (oil etc.)" },
        SLTC: { "instance": "SLTC", "description": "Supervision of on-load tap changers" },
        SOPM: { "instance": "SOPM", "description": "Supervision of operating mechanism for switches (circuit breaker, motor, spring etc.)" },
        SPDC: { "instance": "SPDC", "description": "Supervision of partial discharges" },
        SPRS: { "instance": "SPRS", "description": "General pressure supervision" },
        SPTR: { "instance": "SPTR", "description": "Supervision of power transformers" },
        SSWI: { "instance": "SSWI", "description": "Supervision of the mechanics of disconnectors and grounding switches" },
        STMP: { "instance": "STMP", "description": "General temperature supervision" },
        SVBR: { "instance": "SVBR", "description": "General vibration supervision for rotating machinery" },
        TANG: { "instance": "TANG", "description": "Angle measurement between two physical objects" },
        TAXD: { "instance": "TAXD", "description": "Measurement of axial displacement of a physical object" },
        TCTR: { "instance": "TCTR", "description": "Measurement of electric current using current transformers" },
        TDST: { "instance": "TDST", "description": "Distance measurement to a moving object" },
        TFLW: { "instance": "TFLW", "description": "Measurement of media flow rates of various liquids" },
        TFRQ: { "instance": "TFRQ", "description": "Frequency measurement of non-electrical phenomena (e.g., sounds, vibrations)" },
        TGSN: { "instance": "TGSN", "description": "Measurement functions for a generic sensor" },
        THUM: { "instance": "THUM", "description": "Humidity measurement" },
        TLVL: { "instance": "TLVL", "description": "Measurement of media level/fill level" },
        TMGF: { "instance": "TMGF", "description": "Measurement of magnetic field strength" },
        TMVM: { "instance": "TMVM", "description": "Relative velocity measurement of a physical object" },
        TPOS: { "instance": "TPOS", "description": "Relative position measurement of a movable and physical object" },
        TPRS: { "instance": "TPRS", "description": "General pressure measurement" },
        TRTN: { "instance": "TRTN", "description": "Measurement of the rotational speed of a rotating machine" },
        TSND: { "instance": "TSND", "description": "Measurement of local sound pressure level" },
        TTMP: { "instance": "TTMP", "description": "General temperature measurement" },
        TTNS: { "instance": "TTNS", "description": "General measurement of mechanical tension in a physical object" },
        TVBR: { "instance": "TVBR", "description": "General vibration measurement" },
        TVTR: { "instance": "TVTR", "description": "Measurement of electrical voltage via voltage transformer" },
        TWPH: { "instance": "TWPH", "description": "General measurement of chemical pH levle value" },
        XCBR: { "instance": "XCBR", "description": "Modeling of a circuit breaker" },
        XFUS: { "instance": "XFUS", "description": "Modeling of a fuse switch" },
        XSWI: { "instance": "XSWI", "description": "Modeling of grounding and disconnect switches" },
        YEFN: { "instance": "YEFN", "description": "Modeling of a Petersen coil (power transfomer)" },
        YLTC: { "instance": "YLTC", "description": "Modeling of a tap changer" },
        YPSH: { "instance": "YPSH", "description": "Modeling of a switchable power shunt" },
        YPTR: { "instance": "YPTR", "description": "Modeling of a power transformer" },
        ZAXN: { "instance": "ZAXN", "description": "Modeling of an electrical auxiliary network" },
        ZBAT: { "instance": "ZBAT", "description": "Modeling of a battery" },
        ZBSH: { "instance": "ZBSH", "description": "Modeling of a bushing (busbar)" },
        ZCAB: { "instance": "ZCAB", "description": "Modeling of an power cable (underground cable)" },
        ZCAP: { "instance": "ZCAP", "description": "Modeling of a capacitor bank (MSCDN)" },
        ZCON: { "instance": "ZCON", "description": "Modeling of a converter" },
        ZGEN: { "instance": "ZGEN", "description": "Modeling of a generator" },
        ZGIL: { "instance": "ZGIL", "description": "Modeling of a gas insulated line" },
        ZLIN: { "instance": "ZLIN", "description": "Modeling of an overhead line" },
        ZMOT: { "instance": "ZMOT", "description": "Modeling of a motor" },
        ZREA: { "instance": "ZREA", "description": "Modeling of a reaktor" },
        ZRES: { "instance": "ZRES", "description": "Modeling of a ohmic resistor" },
        ZRRC: { "instance": "ZRRC", "description": "Modeling of a rotating reactive component" },
        ZSAR: { "instance": "ZSAR", "description": "Modeling of a surge arrestor" },
        ZSCR: { "instance": "ZSCR", "description": "Modeling of an electronic controllable rectifier" },
        ZSMC: { "instance": "ZSMC", "description": "Modeling of a synchronous machine" },
        ZTCF: { "instance": "ZTCF", "description": "Modeling of an electrical thyristor controlled frequency converter" },
        ZTCR: { "instance": "ZTCR", "description": "Modeling of an electrical thyristor controlled reactive component"}
    },
    [TypeKind.DOType]: {
        BasePrimitiveCDC: { "instance": "BasePrimitiveCDC", "description": "Common attributes for primitive CDC" },
        BaseComposedCDC: { "instance": "BaseComposedCDC", "description": "Common attributes for composed CDC" },
        SubstitutionCDC: { "instance": "SubstitutionCDC", "description": "Common attributes for substitution" },
        SPS: { "instance": "SPS", "description": "Single point status" },
        DPS: { "instance": "DPS", "description": "Double point status" },
        INS: { "instance": "INS", "description": "Integer status" },
        ENS: { "instance": "ENS", "description": "Enumerated status" },
        ACT: { "instance": "ACT", "description": "Protection activation information" },
        ACD: { "instance": "ACD", "description": "Directional protection indication information" },
        SEC: { "instance": "SEC", "description": "Security violation counting" },
        BCR: { "instance": "BCR", "description": "Binary counter reading" },
        HST: { "instance": "HST", "description": "Histogram" },
        VSS: { "instance": "VSS", "description": "Visible string status" },
        ORS: { "instance": "ORS", "description": "Object reference status" },
        TCS: { "instance": "TCS", "description": "Time value status" },
        HarmonicMeasurandCDC: { "instance": "HarmonicMeasurandCDC", "description": "Common harmonic measurand information" },
        MV: { "instance": "MV", "description": "Measured value" },
        CMV: { "instance": "CMV", "description": "Complex measured value" },
        SAV: { "instance": "SAV", "description": "Sampled value" },
        WYE: { "instance": "WYE", "description": "Phase to ground/neutral related measured values of a 3-phase system" },
        DEL: { "instance": "DEL", "description": "Phase to phase related measured values of a 3-phase system" },
        SEQ: { "instance": "SEQ", "description": "Sequence" },
        HMV: { "instance": "HMV", "description": "Harmonic value" },
        HWYE: { "instance": "HWYE", "description": "Harmonic value for WYE" },
        HDEL: { "instance": "HDEL", "description": "Harmonic value for DEL" },
        ControlTestingCDC: { "instance": "ControlTestingCDC", "description": "Control testing" },
        SPC: { "instance": "SPC", "description": "Controllable single point" },
        DPC: { "instance": "DPC", "description": "Controllable double point" },
        INC: { "instance": "INC", "description": "Controllable integer status" },
        ENC: { "instance": "ENC", "description": "Controllable enumerated status" },
        BSC: { "instance": "BSC", "description": "Binary controlled step position information" },
        ISC: { "instance": "ISC", "description": "Integer controlled step position information" },
        APC: { "instance": "APC", "description": "Controllable analogue process value" },
        BAC: { "instance": "BAC", "description": "Binary controlled analogue process value" },
        SPG: { "instance": "SPG", "description": "Single point setting" },
        ING: { "instance": "ING", "description": "Integer status setting" },
        ENG: { "instance": "ENG", "description": "Enumerated status setting" },
        ORG: { "instance": "ORG", "description": "Object reference setting" },
        TSG: { "instance": "TSG", "description": "Time setting" },
        CUG: { "instance": "CUG", "description": "Currency setting" },
        VSG: { "instance": "VSG", "description": "Visible string setting" },
        ASG: { "instance": "ASG", "description": "Analogue setting" },
        CURVE: { "instance": "CURVE", "description": "Setting curve" },
        CSG: { "instance": "CSG", "description": "Curve shape setting" },
        DPL: { "instance": "DPL", "description": "Device instance plate" },
        LPL: { "instance": "LPL", "description": "Logical node instance plate" },
        CSD: { "instance": "CSD", "description": "Curve shape description" },
        VSD: { "instance": "VSD", "description": "Visible string description" },
        CST: { "instance": "CST", "description": "Common service tracking" },
        BTS: { "instance": "BTS", "description": "Buffered report tracking service" },
        UTS: { "instance": "UTS", "description": "Unbuffered report tracking service" },
        LTS: { "instance": "LTS", "description": "Log control block tracking service" },
        GTS: { "instance": "GTS", "description": "GOOSE control block tracking service" },
        MTS: { "instance": "MTS", "description": "MSVCB tracking service" },
        NTS: { "instance": "NTS", "description": "USVCB tracking service" },
        STS: { "instance": "STS", "description": "SGCB tracking service" },
        CTS: { "instance": "CTS", "description": "Control service tracking" }
    },
    "DAType": {},
    "EnumType": {}
}